### This notebook will focus on finding the best model to predict the severity predictor !

In [184]:
### Libraries we will be using
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, accuracy_score,recall_score,f1_score,roc_curve,roc_auc_score, precision_recall_curve,confusion_matrix,ConfusionMatrixDisplay,classification_report, mean_absolute_error, cohen_kappa_score
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb

In [185]:
## Data set we will be using 
data = pd.read_csv('../Datasets/pre-processedData.csv')
attack_data = data[data['is_malicious'] == 1]
attack_data.drop(columns=['is_malicious', 'Unnamed: 0'], inplace = True)
attack_data.head(5)

/var/folders/bt/9_3kc80d4jq8sv8fv_c7d_fr0000gn/T/ipykernel_64288/3148040238.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attack_data.drop(columns=['is_malicious', 'Unnamed: 0'], inplace = True)

,duration,src_bytes,dst_bytes,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,...,flag_REJ,flag_RSTO,flag_RSTR,flag_S1,flag_S3,flag_SF,flag_SH,Severity_Score,bytes_ratio,total_bytes
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,...,0,0,0,0,0,0,0,2,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,...,1,0,0,0,0,0,0,2,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,...,0,0,0,0,0,0,0,2,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,...,0,0,0,0,0,0,0,2,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0,...,0,0,0,0,0,0,0,2,0.0,0.0

In [186]:
## Train test split of the data 
RANDOM_SEED = 42
X = attack_data.drop(columns=['Severity_Score'])
y = attack_data['Severity_Score']

## Splitting the data into train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=RANDOM_SEED)

---

### Model 1 : Logisitc Regression

In [187]:
### Setting custom class weights based on the severity type 
class_weights = {1:1,2:3, 3:10} 
pipeline_steps = [('scaler', StandardScaler()),('logit', LogisticRegression(solver='lbfgs', class_weight = class_weights,C=1000,penalty='l2',max_iter = 1000))]
logit_pipeline = Pipeline(pipeline_steps)

logit_model = logit_pipeline.fit(X_train,y_train)

/opt/anaconda3/envs/Network_Intrusion/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

In [188]:
logit_training_pred = logit_model.predict(X_train)
logit_testing_pred = logit_model.predict(X_test)
logit_training_proba = logit_model.predict_proba(X_train)[:,1]
logit_testing_proba = logit_model.predict_proba(X_test)[:,1]

In [189]:
## Evaluating the model
logit_mae = mean_absolute_error(y_test, logit_testing_pred)
print(f"{logit_mae:.3f}")

# Cohen Kappa Score 
cks = cohen_kappa_score(y_test, logit_testing_pred)
print(f"{cks:.2f}")


high_severe_testing_data = y_test == 3
high_severe_predicted_test_data = logit_testing_pred == 3

### Confusion Matrix for the severe cases 

true_positives = ((y_test == 3)& (logit_testing_pred == 3)).sum()
false_positives = ((y_test != 3) & (logit_testing_pred == 3)).sum()
false_negatives = ((y_test == 3) & (logit_testing_pred != 3)).sum()
true_negatives = ((y_test != 3) & (logit_testing_pred != 3)).sum()



### Metrics for calculation 
logit_rare_precision = true_positives/(true_positives+false_positives) 
logit_rare_recall = true_positives/(true_positives + false_negatives)
logit_f1_rare = 2*((logit_rare_precision * logit_rare_recall)/(logit_rare_precision + logit_rare_recall))
logit_rare_fpr = false_positives/(true_negatives+false_positives) ## Misclassified
logit_rare_fnr = false_negatives/(true_positives+false_negatives) ## False Alaram

print(logit_rare_precision, logit_rare_recall, logit_rare_fpr, logit_rare_fnr)

0.007
0.99
0.9756986634264885 0.9901356350184957 0.001483459427384661 0.009864364981504316

---
### Model 2: Linear SVM

In [190]:
pipeline_steps = [('scaler', StandardScaler()), ('svm', LinearSVC(multi_class='ovr', penalty='l2', C = 0.1))]
svm_pipeline = Pipeline(pipeline_steps)

best_svm = svm_pipeline.fit(X_train, y_train)

In [191]:
svm_testing_pred = best_svm.predict(X_test)
svm_training_pred = best_svm.predict(X_train)

svm_testing_boundary = best_svm.decision_function(X_test)
svm_training_boundary = best_svm.decision_function(X_train)

In [192]:
### Metrics for evaluation 
svm_mae = mean_absolute_error(y_test, svm_testing_pred)

## Cohen Kappa Score 
svm_cohen_kappa = cohen_kappa_score(y_test, svm_testing_pred)

## Confusion Matrix 

true_positives = ((y_test == 3) & (svm_testing_pred == 3)).sum()
true_negatives = ((y_test != 3) & (svm_testing_pred != 3)).sum()
false_negatives = ((y_test == 3) & (svm_testing_pred != 3)).sum()
false_positives = ((y_test != 3) & (svm_testing_pred == 3 )).sum()


### Precision
svm_precision_rare = true_positives /(true_positives + false_positives)

## Recall
svm_recall_rare = true_positives/(true_positives + false_negatives)

## F1_score 

svm_f1_rare = 2*((svm_precision_rare * svm_recall_rare)/(svm_precision_rare + svm_recall_rare))

### False Positive Rate

svm_fpr = false_positives / (false_positives + true_negatives) ## Misclassified
svm_fnr = false_negatives / (false_negatives + true_positives) ## False Alaram


print(svm_precision_rare, svm_recall_rare, svm_f1_rare, svm_fpr, svm_fnr)

0.9887359198998749 0.9741060419235512 0.9813664596273292 0.0006675567423230974 0.025893958076448828

---
### Model 3: Naive Bayes

In [193]:
naive_model = GaussianNB(var_smoothing=1e-9)
naive_model.fit(X_train, y_train)

GaussianNB()

In [194]:
## Training and testing pred

naive_testing_pred = naive_model.predict(X_test)
naive_training_pred = naive_model.predict(X_train)

naive_testing_proba = naive_model.predict_proba(X_test)
naive_training_proba = naive_model.predict_proba(X_train)

In [195]:
## Metrics for evaluation 

naive_mae = mean_absolute_error(y_test, naive_testing_pred)

## Cohen-Kappa Score

naive_cohen = cohen_kappa_score(y_test, naive_testing_pred)

## Confusion Matrix 

true_positives = ((y_test == 3) & (naive_testing_pred == 3)).sum()
true_negatives = ((y_test != 3) & (naive_testing_pred != 3)).sum()
false_positives = ((y_test != 3) & (naive_testing_pred == 3)).sum()
false_negatives = ((y_test == 3) & (naive_testing_pred != 3)).sum()

### Precision, Recall, F1-Score, fpr, fnr 

naive_precision = true_positives / (true_positives + false_positives)
naive_recall = true_positives / (true_positives + false_negatives)
naive_f1_rare = 2*((naive_precision * naive_recall)/(naive_precision + naive_recall))
naive_fpr = false_positives /(false_positives + true_negatives) ## Misclassified Cases
naive_fnr = false_negatives /(false_negatives + true_positives) ## False Alarm 



print(naive_mae, naive_cohen, naive_precision, naive_recall, naive_fpr, naive_fnr)

0.07535157069894353 0.8457851351117285 0.8656174334140436 0.8816276202219482 0.008233199821984869 0.11837237977805179

---

### Model 4: Decision Tree Classifier

In [196]:
decision_model = DecisionTreeClassifier(criterion='gini', random_state=RANDOM_SEED, max_depth = 10, max_features=12, min_samples_leaf=75, min_samples_split=230)

decision_model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=10, max_features=12, min_samples_leaf=75,
                       min_samples_split=230, random_state=42)

In [197]:
decision_testing_pred = decision_model.predict(X_test)
decision_training_pred = decision_model.predict(X_train)

decision_testing_proba = decision_model.predict_proba(X_test)[:,1]
decision_training_proba = decision_model.predict_proba(X_train)[:,1]

In [198]:
### Metrics for the evaluation 

## Mean Absoulute Error 
decision_mae = mean_absolute_error(y_test, decision_testing_pred)

## Cohen Kappa's 


decision_cohen = cohen_kappa_score(y_test, decision_testing_pred)

## Confusion matrix 

true_positives = ((y_test ==3) & (decision_testing_pred == 3)).sum()
true_negatives = ((y_test != 3) & (decision_testing_pred != 3)).sum()
false_positives = ((y_test != 3) & (decision_testing_pred == 3)).sum()
false_negatives = ((y_test == 3) & (decision_testing_pred != 3)).sum()


## Precision, recall and f1 score 


decision_precision = true_positives / (true_positives + false_positives)
decision_recall = true_positives / (true_positives + false_negatives)
decision_fpr = false_positives  / (false_positives + true_negatives) ##Mis classification error 
decision_fnr = false_negatives / (false_negatives + true_positives) ## False Alarm
decision_f1 = 2 * ((decision_precision * decision_recall) / (decision_precision + decision_recall))


print(decision_precision, decision_recall, decision_fpr, decision_fnr, decision_f1)

0.9509433962264151 0.9321824907521579 0.002892745883400089 0.06781750924784218 0.9414694894146949

---
### Model 5: Random Forest Classifier

In [199]:
estimators = [100,200,300,400,500]
oob_scores = []
for n in estimators:
    random_model = RandomForestClassifier(oob_score = True , n_estimators= n, min_samples_leaf=70, min_samples_split=160, max_depth = 12, max_features=8)
    random_model.fit(X_train,y_train)
    oob_scores.append(random_model.oob_score_)

In [200]:
random_model = RandomForestClassifier(criterion='gini', n_estimators=200, oob_score=True, max_depth = 11, max_features= 10, min_samples_leaf=70, min_samples_split=200, random_state= RANDOM_SEED)
random_model.fit(X_train,y_train)

RandomForestClassifier(max_depth=11, max_features=10, min_samples_leaf=70,
                       min_samples_split=200, n_estimators=200, oob_score=True,
                       random_state=42)

In [201]:
random_testing_pred = random_model.predict(X_test)
random_training_pred = random_model.predict(X_train)

random_testing_proba = random_model.predict_proba(X_test)
random_training_proba = random_model.predict_proba(X_train)

In [202]:
### Metrics for evaluation 

random_mae = mean_absolute_error(y_test, random_testing_pred)

## Cohen Kappa
random_cohen = cohen_kappa_score(y_test, random_testing_pred)

## Confusion Matrix 

## Confusion matrix 

true_positives = ((y_test ==3) & (random_testing_pred == 3)).sum()
true_negatives = ((y_test != 3) & (random_testing_pred != 3)).sum()
false_positives = ((y_test != 3) & (random_testing_pred == 3)).sum()
false_negatives = ((y_test == 3) & (random_testing_pred != 3)).sum()


## Precision, recall and f1 score 


random_precision = true_positives / (true_positives + false_positives)
random_recall = true_positives / (true_positives + false_negatives)
random_fpr = false_positives  / (false_positives + true_negatives) ##Mis classification error 
random_fnr = false_negatives / (false_negatives + true_positives) ## False Alarm
random_f1 = 2 * ((decision_precision * decision_recall) / (decision_precision + decision_recall))


print(random_precision, random_recall, random_fpr, random_fnr, random_f1)

0.9961340206185567 0.9531442663378545 0.00022251891410769915 0.0468557336621455 0.9414694894146949

---
### Model 6: XGBoost

In [203]:

## Only for XGBModel :
attack_data['Severity_Score'] = attack_data['Severity_Score'].map({1:0,2:1,3:2})
X = attack_data.drop(columns=['Severity_Score'])
y = attack_data['Severity_Score']

## Splitting the data into train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=RANDOM_SEED)

xgb_model = xgb.XGBClassifier(learning_rate = 1, n_estimators = 43, max_depth = 6, colsample_bytree = 0.6,objective="multi:softmax", reg_lambda = 0.1, subsample = 0.7, min_child_weight = 2)

xgb_model.fit(X_train,y_train)

/var/folders/bt/9_3kc80d4jq8sv8fv_c7d_fr0000gn/T/ipykernel_64288/733552882.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attack_data['Severity_Score'] = attack_data['Severity_Score'].map({1:0,2:1,3:2})

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.6, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=2, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=43,
              n_jobs=None, num_parallel_tree=None, ...)

In [204]:
## Training and Testing Score

xgb_training_score = xgb_model.predict(X_train)
xgb_testing_score = xgb_model.predict(X_test)

print((xgb_testing_score == 1).sum())

xgb_training_proba = xgb_model.predict_proba(X_train)
xgb_testing_proba = xgb_model.predict_proba(X_test)

10707

In [205]:
## Metrics of evaluation 

xgb_mae = mean_absolute_error(y_test, xgb_testing_score)


## Cohen Kappa's score

xgb_cohen = cohen_kappa_score(y_test, xgb_testing_score)


## Confusion matrix 

true_positives = ((y_test ==2) & (xgb_testing_score == 2)).sum()
true_negatives = ((y_test != 2) & (xgb_testing_score != 2)).sum()
false_positives = ((y_test != 2) & (xgb_testing_score == 2)).sum()
false_negatives = ((y_test == 2) & (xgb_testing_score != 2)).sum()


## Precision, recall and f1 score 


xgb_precision = true_positives / (true_positives + false_positives)
xgb_recall = true_positives / (true_positives + false_negatives)
xgb_fpr = false_positives  / (false_positives + true_negatives) ##Mis classification error 
xgb_fnr = false_negatives / (false_negatives + true_positives) ## False Alarm
xgb_f1 = 2 * ((xgb_precision * xgb_recall) / (xgb_precision +xgb_recall))


print(xgb_precision, xgb_recall, xgb_fpr, xgb_fnr, xgb_f1)

0.9975247524752475 0.9938347718865598 0.0001483459427384661 0.006165228113440197 0.9956763434218652

---
### Lets see how did every model perform in terms of severity classification !

In [208]:
model_name = ['LR', 'SVM', 'GaussianNB', 'DecisionTrees', 'RandomForest', 'XGBoost']

## Model's Mean-Absolute Error

model_mae = [logit_mae, svm_mae, naive_mae, decision_mae, random_mae, xgb_mae]

## Model's Cohen Kappa Score

model_cohen = [cks, svm_mae, naive_mae, decision_mae, random_mae, xgb_mae]

## Model's precision score

model_precision = [logit_rare_precision, svm_precision_rare, naive_precision, decision_precision, random_precision, xgb_precision]

## Model's Recall Score

model_recall = [logit_rare_recall, svm_recall_rare, naive_recall, decision_recall, random_recall, xgb_recall]

## Model's F1 Score

model_f1 = [logit_f1_rare, svm_f1_rare, naive_f1_rare, decision_f1,random_f1, xgb_f1]

## Misclassification 
misclassification_error = [logit_rare_fpr, svm_fpr,naive_fpr, decision_fpr, random_fpr, xgb_fpr]

## False Alarm

false_alarm = [logit_rare_fnr,svm_fnr,naive_fnr,decision_fnr, random_fnr, xgb_fnr]
severity_classifiers = pd.DataFrame(
{
    'model_name': model_name,
    'model_mae': model_mae,
    'model_cohen':model_cohen,
    'precision_rare_attacks':model_precision,
    'recall_rare_attacks': model_recall,
    'f1_rare_attacks': model_f1,
    'Misclassified_attacks':misclassification_error,
    'false_alarm':false_alarm
}
)

severity_classifiers.head(6)

,model_name,model_mae,model_cohen,precision_rare_attacks,recall_rare_attacks,f1_rare_attacks,Misclassified_attacks,false_alarm
0,LR,0.007416,0.986266,0.975699,0.990136,0.982864,0.001483,0.009864
1,SVM,0.007066,0.007066,0.988736,0.974106,0.981366,0.000668,0.025894
2,GaussianNB,0.075352,0.075352,0.865617,0.881628,0.873549,0.008233,0.118372
3,DecisionTrees,0.015252,0.015252,0.950943,0.932182,0.941469,0.002893,0.067818
4,RandomForest,0.006996,0.006996,0.996134,0.953144,0.941469,0.000223,0.046856
5,XGBoost,0.001189,0.001189,0.997525,0.993835,0.995676,0.000148,0.006165